### ISSUE TITLE
NoSuchMethodException crash 

### ISSUE THREAD

**Issue by devgianlu** [devgianlu/DNSHero#7]
```
OS Version: 3.18.71-g80b065a(0a383a5192)
OS API Level: 27
Device: marmite
Model (and Product): Swift 2 X (Swift2)
Application version: 1.2.0
Crashlytics UID: null

java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [class com.gianlu.dnshero.NetIO.b$g, class org.json.JSONObject]
at com.gianlu.commonutils.b.a(CommonUtils.java:555)
at com.gianlu.dnshero.NetIO.b$g.<init>(Domain.java:181)
at com.gianlu.dnshero.NetIO.b$j.<init>(Domain.java:207)
at com.gianlu.dnshero.NetIO.b.<init>(Domain.java:30)
at com.gianlu.dnshero.NetIO.ZoneVisionAPI$1.run(ZoneVisionAPI.java:51)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NoSuchMethodException: <init> [class com.gianlu.dnshero.NetIO.b$g, class org.json.JSONObject]
at java.lang.Class.getConstructor0(Class.java:2320)
at java.lang.Class.getDeclaredConstructor(Class.java:2166)
at com.gianlu.commonutils.b.a(CommonUtils.java:541)
... 7 more
```

**Comment by Sm0ke0ut** [comment]
Doesn't seem to be fixed;
```
OS Version: 3.18.71-g80b065a(0a383a5192)
OS API Level: 27
Device: marmite
Model (and Product): Swift 2 X (Swift2)
Application version: 1.2.2
Crashlytics UID: null

java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [class com.gianlu.dnshero.NetIO.a, class org.json.JSONObject]
at com.gianlu.commonutils.b.a(CommonUtils.java:555)
at com.gianlu.dnshero.NetIO.a.<init>(DNSRecord.java:19)
at com.gianlu.dnshero.NetIO.b$i.<init>(Domain.java:71)
at com.gianlu.dnshero.NetIO.b$i.a(Domain.java:78)
at com.gianlu.dnshero.NetIO.b$c.<init>(Domain.java:124)
at com.gianlu.dnshero.NetIO.b.<init>(Domain.java:31)
at com.gianlu.dnshero.NetIO.ZoneVisionAPI$1.run(ZoneVisionAPI.java:51)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NoSuchMethodException: <init> [class com.gianlu.dnshero.NetIO.a, class org.json.JSONObject]
at java.lang.Class.getConstructor0(Class.java:2320)
at java.lang.Class.getDeclaredConstructor(Class.java:2166)
at com.gianlu.commonutils.b.a(CommonUtils.java:541)
... 9 more
```

**Comment by devgianlu** [comment]
I can't reproduce this, but I know how to fix it.
